### ISSUE TITLE
IWritable not found

### ISSUE THREAD

**Issue by BenjaminHalko** [kitlith/GotaSequenceCmd#2]
It keeps on giving me the error message:
`error CS0246: The type or namespace name 'IWritable' could not be found (are you missing a using directive or an assembly reference?)` 

I have already loaded in the other 2 libraries

**Comment by BenjaminHalko** [comment]
Nevermind. I fixed it by renaming `IWritable` to `IWriteable`

**Comment by kitlith** [comment]
hm. apologies, because I don't think that was in code I wrote at all. did the name change in one of the libraries?

**Comment by BenjaminHalko** [comment]
It was in this [file](https://github.com/kitlith/GotaSequenceCmd/blob/master/CommonStructures.cs) where the problem lies. Maybe the variable `IWriteable` was misspelled in GotaSoundIO and was spelled `IWritable`. But when they fixed the spelling error, your code broke. Maybe update your code to match the current GotaSoundIO spelling.

**Comment by kitlith** [comment]
send a pr and i'll merge it. unfortunately, all the context for this stuff has mostly left my head, and i don't use the tool myself, so otherwise it's probably going to continue unmaintained.

Yes I realized it was that file, my comment is because I pulled that file from some other code that Gota wrote (don't ask me where, i don't remember) for use in conjunction with GotaSoundIO, because they had already written all that stuff for handling Revolution file formats.

this repo is just a small shim around code that Gota wrote, and iirc they wrote their own tool that does the same thing except maybe it didn't expose the midi stuff.

**Comment by BenjaminHalko** [comment]
Here you go: #3

**Comment by BenjaminHalko** [comment]
#3

**Comment by kitlith** [comment]
Merged.
